In [ ]:
import numpy as np 

In [ ]:
data1 = [1,2,3,4,5]
data1

[1, 2, 3, 4, 5]

In [ ]:
data2 = [1,2,3,5,4]
data2

[1, 2, 3, 5, 4]

In [ ]:
arr1 = np.array(data1)
arr1

array([1, 2, 3, 4, 5])

In [ ]:
arr2 = np.array([1,2,3,4,5])
arr2

array([1, 2, 3, 4, 5])

In [ ]:
arr2.shape

(5,)

In [ ]:
arr2.dtype

dtype('int64')

In [ ]:
arr4 = np.array([[1,2,3], [4,5,6], [7,8,9]])
arr4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr4.shape

(3, 3)

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.ones(9)

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(3,11)

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[10,11,12],[13,14,15]])

In [ ]:
arr1*arr2

array([[10, 22, 36],
       [52, 70, 90]])

In [ ]:
names = np.array(['A','B','C','D','E','F','G','H'])
names

array(['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H'], dtype='<U1')

In [ ]:
names.shape

(8,)

In [ ]:
data = np.random.randn(8,4)
data

array([[ 0.84947028, -0.44437645, -0.4557666 ,  0.59999617],
       [ 1.08298466, -0.26288334, -0.17914089,  0.64086875],
       [-1.60991828,  0.54927069,  0.34884968,  0.02349846],
       [-1.11658798,  1.41226976, -0.92775536, -0.38350867],
       [-1.14105258, -0.75352318, -0.8312143 ,  0.21033619],
       [-0.93067076,  0.01638141,  0.81041091,  0.74008278],
       [ 0.45874942, -0.0071861 ,  0.28752205,  0.29839354],
       [ 1.40462793,  2.57302712, -0.30761435,  1.01640349]])

In [ ]:
data.shape

(8, 4)

In [ ]:
names_A_mask = (names == 'A')
names_A_mask

array([ True, False, False, False, False, False, False, False])

In [ ]:
data[names_A_mask, :]

array([[ 0.84947028, -0.44437645, -0.4557666 ,  0.59999617]])

In [ ]:
data[names == 'B', :]

array([[ 1.08298466, -0.26288334, -0.17914089,  0.64086875]])

In [ ]:
#먼저 마스크를 만든다.
#data array에서 0번째 열이 0보다 작은 요소의 boolean 값
data[:,0] <0

array([False, False,  True,  True,  True,  True, False, False])

In [ ]:
#0번째 열의 값이 0보다 작은 행의 2,3번째 열 값
data[data[:,0]<0, 2:4]

array([[ 0.34884968,  0.02349846],
       [-0.92775536, -0.38350867],
       [-0.8312143 ,  0.21033619],
       [ 0.81041091,  0.74008278]])

In [ ]:
np.sign(arr1)

array([[1, 1, 1],
       [1, 1, 1]])

In [ ]:
np.tanh(arr1)

array([[0.76159416, 0.96402758, 0.99505475],
       [0.9993293 , 0.9999092 , 0.99998771]])